name: Build sql db & publish to artifact
on: workflow_dispatch
#  push:
#    branches:
#      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up SQL Server
      uses: microsoft/setup-msbuild@v1
      with:
        accept-eula: true
        sql-package-exe-download-path: 'https://go.microsoft.com/fwlink/?linkid=2069140&clcid=0x409'
        
    - name: Build database
      run: |
        sqlcmd -S localhost -U admin -P admin123 -i ./src/DB/AdventureWorks2017.sql
      
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: database
        path: ${{ github.workspace }}/bin/Release/
